[package]
name = "rit"
version = "0.1.0"
authors = ["Bhargav Voleti <bhargav.voleti93@gmail.com>"]
edition = "2018"

[dependencies]
rust-crypto = "0.2.36"
bytes = "0.4.12"
rand = "0.6"
flate2 = "1.0.7"
pretty_env_logger = "0.3.0"
log = "0.4"
derive_more = "0.15.0"
